### ISSUE TITLE
Compatibility with Nougat?

### ISSUE THREAD

**Issue by geekywoman** [aegis1980/WifiHotSpot#4]
Hi,

First of all, thank you for your contribution. I found your post on stackoverflow and your app might be able to save my life (or almost :D).

It is working great on Oreo devices. But I am facing an issue on devices running on Nougat versions. The hotspot turns on without any problem. But when you try to connect from another device to it you stay stuck on "Obtaining IP address..." forever.
This method is working for lower versions than Nougat, for versions above also. But not Nougat itself. And guess what? I am the lucky person who need it to be working on Nougat!

Would you have any idea how to handle it or insight that would help to figure this out?

Many thanks in advance!

**Comment by geekywoman** [comment]
**Note:** If you apply the Oreo method to Nougat you obtain the following error

```
05-18 13:40:42.984 3540-4864/com.fitc.wifihotspot W/System.err: Caused by: java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query user
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.net.IConnectivityManager$Stub$Proxy.startTethering(IConnectivityManager.java:1628)
        at android.net.ConnectivityManager.startTethering(ConnectivityManager.java:2104)
        at android.net.ConnectivityManager.startTethering(ConnectivityManager.java:2068)
    	... 8 more
```

And as MANAGE_USERS or CREATE_USERS is a system permission... :( 

Looks like the issue of being stuck on the "Obtaining IP address.." is very well known among 7.1.* version users.. Due to a DHCP failure from Android itself. This issue is only triggered when a third party app is starting the hotspot though. If you enable it manually from the system settings it does not occur.

**Comment by geekywoman** [comment]
I have been doing some research on the subject and I found this app that is actually successful to enable tether even 7.1.* 
https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm
But how are they managing to do it.. That is the question.

**Comment by aegis1980** [comment]
Hey,
I only really wrote code to sort out my own issues with hotspot on Oreo.
Pretty sure nougat has its own set of problems-and-solutions with wifi
toggling; but they're all pretty different from (my) fixes for oreo. From
memory, google changed pretty much everything under the bonnet for
hotspotting when oreo came out.
Jon

**Comment by geekywoman** [comment]
Hey Jon,
Yes unfortunately it is pretty much different. Nougat is a version "in-between", the old way of doing it is not working and neither is the oreo work around :(
Anyway, thank you very much for sharing this. To know that there is a oreo solution is very helpful

**Comment by geekywoman** [comment]
For what it is worth, here is my solution, if it can help anyone:
https://github.com/geekywoman/direct-net-share
We take advantage of the root rights to do the magic with the DHCP so the user does not need to setup any proxy manually.

Huge thanks to shinilms and his demo app (no-root):
https://github.com/shinilms/direct-net-share
(it enables the hotspot and requires the user to setup a proxy on his phone)
